### ISSUE TITLE
Test suite failure

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/repo2docker-action#117]
```
Build localhost:5000/repo2docker-test:fc2ede81dc9b
  Picked Local content provider.
  Using local repo /github/workspace.
  Using DockerBuildPack builder
  Traceback (most recent call last):
    File "/opt/venv/bin/jupyter-repo2docker", line 8, in <module>
      sys.exit(main())
               ^^^^^^
    File "/opt/venv/lib/python3.11/site-packages/repo2docker/__main__.py", line 474, in main
      r2d.start()
    File "/opt/venv/lib/python3.11/site-packages/repo2docker/app.py", line 892, in start
      self.build()
    File "/opt/venv/lib/python3.11/site-packages/repo2docker/app.py", line 856, in build
      for l in picked_buildpack.build(
    File "/opt/venv/lib/python3.11/site-packages/repo2docker/buildpacks/docker.py", line 65, in build
      yield from client.build(**build_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/venv/lib/python3.11/site-packages/repo2docker/docker.py", line 97, in build
      return self._apiclient.build(
             ^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/venv/lib/python3.11/site-packages/docker/api/build.py", line 134, in build
      raise errors.DockerException(
  docker.errors.DockerException: invalid tag 'localhost:5000/repo2docker-test:fc2ede81dc9b': invalid reference format
```

**Comment by consideRatio** [comment]
Last successful tests were 28 November 2023. Since then the Python docker client 7.0.0 has been released - I presume this is related.

**Comment by consideRatio** [comment]
Reported in https://github.com/docker/docker-py/issues/3240
