### ISSUE TITLE
use github actions cache for docker build

### ISSUE THREAD

**Issue by itcarroll** [jupyterhub/repo2docker-action#126]
**Is your feature request related to a problem? Please describe.**
The repo2docker-action takes a while, and most of that time is spent building docker layers that have not changed. On a local system, Docker would use its layer cache and take less time.

**Describe the solution you'd like**
GitHub Actions provides a way to persist a cache from a runner, and Docker appears to have documentation about using it at: https://docs.docker.com/build/cache/backends/gha/. Could the repo2docker-action integrate such a mechanism, so that Docker images could be built using a cache?

**Comment by itcarroll** [comment]
I [can get custom cache arguments](https://github.com/itcarroll/repo2docker-action/blob/cc5bad9abae7c3ff4ee6cdcfdbcecc9a53d40d0f/create_docker_image.sh#L127-L128) to the build using `--DockerEngine.extra_buildx_build_args`, but run into the following error from the default docker driver. This is why actions/docker-setup-buildx is called before actions/build-and-push-docker-images in docker workflows.

```
Build ghcr.io/itcarroll/bigsnakelock:2ba96bc3cdcd
  Picked Local content provider.
  Using local repo /github/workspace.
  Building conda environment for python=3.12
  Using CondaBuildPack builder
  github.com/docker/buildx v0.19.1 5113f9ea89afd597302961caf99cecd142c7ba05
  ERROR: Cache export is not supported for the docker driver.
  Switch to a different driver, or turn on the containerd image store, and try again.
  Learn more at https://docs.docker.com/go/build-cache-backends/
  Traceback (most recent call last):
    File "/opt/venv/bin/jupyter-repo2docker", line 8, in <module>
      sys.exit(main())
               ^^^^^^
    File "/opt/venv/lib/python3.12/site-packages/repo2docker/__main__.py", line 476, in main
      r2d.start()
    File "/opt/venv/lib/python3.12/site-packages/repo2docker/app.py", line 846, in start
      self.build()
    File "/opt/venv/lib/python3.12/site-packages/repo2docker/app.py", line 809, in build
      for l in picked_buildpack.build(
               ^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/venv/lib/python3.12/site-packages/repo2docker/buildpacks/base.py", line 672, in build
      yield from client.build(**build_kwargs)
    File "/opt/venv/lib/python3.12/site-packages/repo2docker/docker.py", line 162, in build
      yield from execute_cmd(args, True)
    File "/opt/venv/lib/python3.12/site-packages/repo2docker/utils.py", line 76, in execute_cmd
      raise subprocess.CalledProcessError(ret, cmd)
  subprocess.CalledProcessError: Command '['docker', 'buildx', 'build', '--progress', 'plain', '--build-arg', 'NB_USER=jovyan', '--build-arg', 'NB_UID=1000', '--build-arg', 'REPO_DIR=/tmp', '--tag', 'ghcr.io/itcarroll/bigsnakelock:2ba96bc3cdcd', '--platform', 'linux/amd64', '--cache-from=type=registry,ref=ghcr.io/itcarroll/bigsnakelock:buildcache', '--cache-to=type=registry,ref=ghcr.io/itcarroll/bigsnakelock:buildcache,mode=max', '/tmp/tmp31_nk3i8']' returned non-zero exit status 1.
```

**Comment by itcarroll** [comment]
I'm failing to get the containerd image store enabled. I've included the [documented configuration file](https://docs.docker.com/engine/storage/containerd/#enable-containerd-image-store-on-docker-engine) in the `repo2docker-action` Dockerfile. But this is docker-in-docker and I suspect that configuration is meaningless.
